In [1]:
# This code block imports all the necessary libraries needed

import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# read dataset

df = pd.read_csv("energydata.csv")
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [3]:
# dropping the ['date', 'lights'] columns 

df1 = df.drop(['date','lights'],axis=1)
df1.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) 
and the temperature outside the building (y = T6). 
What is the R^2 value in two D.P?

In [10]:
X = df1['T2'].values.reshape(-1,1)
y = df1['T6'].values.reshape(-1,1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

y_predict = linear_model.predict(X_test)
r2 = r2_score(y_test, y_predict)
round(r2,2)

0.64

In [12]:
#F Normalise dataset to a common scale using the minmax scaler

scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df1), columns=df1.columns)

features_df = normalised_df.drop(columns =['Appliances'], axis=1)
target = normalised_df['Appliances']

# Split the dataset into training and testing dataset

X_train,X_test,y_train,y_test = train_test_split(features_df, target, test_size=0.3, random_state=42)
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

#get predictions
predicted_values = linear_model.predict(X_test)
predicted_values

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

What is the mean absolute error (in two decimal places)

In [13]:
# mean_absolute_error

mean_absolute_error = mean_absolute_error(y_test, predicted_values)
round(mean_absolute_error, 2)

0.05

What is the Residual sum of square(in two decimal places)

In [14]:
# Residual sum of square

residual_sum_of_square = np.sum(np.square(y_test - predicted_values))
round(residual_sum_of_square, 2)

45.35

What is the root mean sqaure error (in three decimal places)

In [15]:
# root mean sqaure error  
root_mean_sqaure_error = np.sqrt(mean_squared_error(y_test, predicted_values))
round(root_mean_sqaure_error, 3)

0.088

What is the coefficient of determination (in two decimal places)

In [16]:
# coefficient of determination is the same as Rsquare

from sklearn.metrics import r2_score 
r2 = r2_score(y_test, predicted_values)
round(r2,2)

0.15

obtain the features weight from the model

In [19]:
# compare the weigts of the features after regularization

def get_weights_df(model, feat, col_name):
    
# returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['features_df', col_name]
    weights_df[col_name].round(3)
    return weights_df
linear_model_weights = get_weights_df(linear_model, X_train, 'Linear_Model_Weight')
linear_model_weights

    features_df  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv2             0.000770
11          rv1             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

What is the new root mean square error with the Lasso Regression

In [27]:
# compute lasso regression and ridge
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)

ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(X_train, y_train)


def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()    
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['features_df', col_name]
    weights_df[col_name].round(3)
    return weights_df


lasso_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso_weight')
ridge_weights_df = get_weights_df(ridge_reg, X_train, 'Ridge_Weight')

weights = pd.merge(ridge_weights_df, lasso_weights_df, on='features_df')
weights

    features_df  Ridge_Weight  Lasso_weight
0          RH_2     -0.401134     -0.000000
1         T_out     -0.250765      0.000000
2            T2     -0.193880      0.000000
3            T9     -0.188584     -0.000000
4          RH_8     -0.156596     -0.000110
5        RH_out     -0.050541     -0.049557
6          RH_7     -0.046291     -0.000000
7          RH_9     -0.041701     -0.000000
8            T1     -0.021549      0.000000
9            T5     -0.020727     -0.000000
10          rv1      0.000743     -0.000000
11          rv2      0.000743     -0.000000
12  Press_mm_hg      0.006516     -0.000000
13           T7      0.010021     -0.000000
14   Visibility      0.012032      0.000000
15         RH_5      0.016176      0.000000
16         RH_4      0.024168      0.000000
17           T4      0.027006     -0.000000
18    Windspeed      0.030463      0.002912
19         RH_6      0.035023     -0.000000
20    Tdewpoint      0.076668      0.000000
21         RH_3      0.094976      0.000000
22           T8      0.100754      0.000000
23           T6      0.213316      0.000000
24           T3      0.287408      0.000000
25         RH_1      0.511932      0.017880

Train a ridge regression model with an alpha value of 0.4. check if there is any change in root mean square error if evaluated on the test set

In [32]:
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(X_train, y_train)


def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()    
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['features_df', col_name]
    weights_df[col_name].round(3)
    return weights_df


ridge_weights_df = get_weights_df(ridge_reg, X_train, 'Ridge_Weight')
ridge_weights_df

    features_df  Ridge_Weight
0          RH_2     -0.411071
1         T_out     -0.262172
2            T2     -0.201397
3            T9     -0.188916
4          RH_8     -0.156830
5        RH_out     -0.054724
6          RH_7     -0.045977
7          RH_9     -0.041367
8            T5     -0.019853
9            T1     -0.018406
10          rv2      0.000748
11          rv1      0.000748
12  Press_mm_hg      0.006584
13           T7      0.010098
14   Visibility      0.012076
15         RH_5      0.016152
16         RH_4      0.024579
17           T4      0.027384
18    Windspeed      0.030268
19         RH_6      0.035519
20    Tdewpoint      0.083128
21         RH_3      0.095135
22           T8      0.101028
23           T6      0.217292
24           T3      0.288087
25         RH_1      0.519525

What is the new root mean square error with the lasso regression (in 3 decimal places)

In [34]:
#New Root Mean Square Error 
from sklearn.metrics import  mean_squared_error
root_mean_squared_error = np.sqrt(mean_squared_error(y_test, predicted_values))
round (root_mean_squared_error, 3)


# there is no effect on the rmse

0.088

What is the new root mean square eror(RMSE) with Lasso Regression

In [35]:
# root_mean_squared_error with lasso

lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
lasso_predict = lasso_reg.predict(X_test)

rmse_lasso =np.sqrt(mean_squared_error(y_test, lasso_predict))
round(rmse_lasso,3)

0.094